name: user_location_repository
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.0
  uuid: ^3.0.0
  google_maps_flutter: ^2.5.3
  geolocator: ^11.0.0
  logger: ^2.2.0
